### ISSUE TITLE
Using filter() on a column with NA values

### ISSUE THREAD

**Issue by sgriff** [ucsb-bren/students#86]
For my individual assignment, I'm trying to filter a column that has some NA values to show values that are above a threshold. R comes back with:

> sgriff_loadyields %>%
> - select(state:nitrogen) %>%
> - filter(nitrogen >= 1000) %>%
> - summarize(n = n())
>   n
>   1 0
>   Warning message:
>   In Ops.factor(c(29L, NA, NA, 34L, NA, 39L, 1L, 4L, 19L, 22L, NA,  :
>   ‘>=’ not meaningful for factors

 I've tried many different combos of using na.omit, na.strings"", or na.rm=TRUE, or as.numeric. I don't know how else to filter using this dataset.

**Comment by bbest** [comment]
Hi @sgriff,

Ok, the problem here is that the `nitrogen` column has commas as thousands separator so R calls it a factor when you use `read.csv` (or would type it as character if you use `readr::read_csv`). To conver to numeric, dplyr allows you to create or change fields with the `mutate()` function. To manipulate strings, I also recommend using the `stringr` library. For instance:

``` r
sgriff_loadyields %>%
  select(state:nitrogen) %>%
  mutate(nitrogen = as.numeric(stringr::str_replace_all(nitrogen,',',''))) %>%
  filter(nitrogen >= 1000)
```

Look at that result before you go on to summarize to ensure you're answering the right question. If you wanted to ask how many states have nitrogen load yields higher than 1,000, then what you had is correct:

``` r
sgriff_loadyields %>%
  select(state:nitrogen) %>%
  mutate(nitrogen = as.numeric(stringr::str_replace_all(nitrogen,',',''))) %>%
  filter(nitrogen >= 1000) %>%
  summarize(n = n()) 
```

In future, please push your code to your `sgriff/env-info`. You're welcome to make a pull request to `ucsb-bren/env-info` to flag an issue. With either of these methods I can see the full state of affairs with your code (eg your question for above). Including the snippet above worked fine for now.
